### ISSUE TITLE
RTFM and could not make pint[Mt CO2] work as a unit

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [openscm/openscm-units#32]
I've spent a good hour probing docs(and sample notebooks) between openscm-units, openscm, pint, and pint-pandas.  What I have not figured out how to do is make this work:

```
import pandas as pd
import pint_pandas
from openscm_units import unit_registry
one_co2 = unit_registry("CO2")
print(one_co2)

x = pd.DataFrame([[1.0,'Mt CO2']], columns=['Value', 'Unit'])
x.astype({'Value': 'pint[Mt CO2]'}).dtypes
```

My one_co2 is 1 CO2, but pint complains: UndefinedUnitError: 'CO2' is not defined in the unit registry

What am I missing?  What changes could I help put into the docs for others to use openscm-units successfully?

**Comment by mikapfl** [comment]
Hi,

could you post a minimum reproducing example of what you are trying to do? Running the code you posted, I get:
```python
NameError                                 Traceback (most recent call last)
<ipython-input-1-c1071259d82c> in <module>
      2 one_co2 = unit_registry("CO2")
      3 
----> 4 x = shell_df[shell_df['Unit']=='Mt CO2']
      5 x.astype({'Value': 'pint[Mt CO2]'}).dtypes

NameError: name 'shell_df' is not defined
```
And I'm not completely sure what you are trying to do.

Cheers,

Mika

**Comment by MichaelTiemannOSC** [comment]
Fixed code so you can run it.  Sorry!

**Comment by mikapfl** [comment]
Hi,

I haven't worked much with pint-pandas (I did more using pint-xarray because we decided for xarray instead of pandas), but from what I gather the *experimental* unit support using `pint-pandas` can be used with custom unit registries like this:

```python
import pandas as pd
import pint_pandas
from openscm_units import unit_registry

# start using the custom unit registry
pint_pandas.PintType.ureg = unit_registry

x = pd.DataFrame({'value': pd.Series([1.0], dtype='pint[Mt CO2]')})

x["value"].pint.to('CH4 kt', 'SARGWP100')
```
Which will output:
```
0    47.61904761904762
Name: value, dtype: pint[CH4 * kt]
```

But note that the integration between pandas and pint is experimental, so probably this code will not work next year anymore because something was changed. Also setting the unit registry on the `PintType` is not exactly a clean way to do things.

`openscm-units` itself is a pint-only library, so the difficulty of integrating pint with pandas is not fully in scope for the docs - but probably some chapter in the docs on integrations with other libraries would be useful?

Cheers,

Mika

**Comment by znicholls** [comment]
Thanks for the responses @mikapfl!

@MichaelTiemannOSC, @mikapfl is right that the pint-pandas integration is a little flimsy at times. You can probably tell that by looking at the number of open issues and pull requests in the pint-pandas repository. The current development path is currently stuck by, essentially, this issue https://github.com/pandas-dev/pandas/issues/35131. If you want to dig deeper, see also https://github.com/pandas-dev/pandas/issues/43196 (essentially duplicate of first issue), https://github.com/pandas-dev/pandas/issues/43195 (same as previous but with slightly more info), https://github.com/pandas-dev/pandas/pull/35127 https://github.com/pandas-dev/pandas/pull/39790/files https://github.com/pandas-dev/pandas/pull/39830 (PRs attempting to implement fixes which all stalled as this seems to not be anyone's priority unfortunately).
